kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build_code
  image: perl
  commands:
  - perl build_config.pl

---
kind: pipeline
type: ssh
name: deploy

server:
  host: homeassistant.private.simcop2387.info
  user: esphome_remote
  password:
    from_secret:  esphome_remote_pass

steps:
- name: greeting
  commands:
  - echo hello world

