kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

node:
  vlan: priviliged

steps:
- name: build_code
  image: perl
  commands:
  - cpanm --installdeps .
  - perl build_config.pl

- name: gitea_release
  image: plugins/gitea-release
  settings:
    files: garden-watering.yml
  when:
    event: tag

- name: build_docker
  image: docker
  volumes:
  - name: dockersock
    path: /var/run/docker.sock
  commands:
  - docker build -t ssh-runner:latest

- name: upload
  image: plugins/s3
  settings:
    bucket: drone
    access_key:
      from_secret: drone_minio_user
    secret_key:
      from_secret: drone_minio_pass
    source: garden-watering.yaml
    target: /garden-water/
    path_style: true
    endpoint: http://192.168.1.229:9000

- name: push_to_homeass
  image: ssh-runner:latest
  secrets: [ha_ssh_key]
  environment: 
    SSH_KEY:
      from_secret: ha_ssh_key
  commands:
    - mkdir /root/.ssh && echo "$${SSH_KEY}" > /root/.ssh/id_ed25519 && chmod 0600 /root/.ssh/id_ed25519
    - ssh -oStrictHostKeyChecking=no root@homeassistant.home.simcop2387.info -p 22222 'cd /mnt/data/supervisor/homeassistant/esphome; curl http://192.168.1.229:9000/drone/garden-water/garden-watering.yaml -o garden-watering.yaml'

- name: homeass_compile
  image: ssh-runner:latest
  secrets: [ha_ssh_key]
  environment: 
    SSH_KEY:
      from_secret: ha_ssh_key
  commands:
    - mkdir /root/.ssh && echo "$${SSH_KEY}" > /root/.ssh/id_ed25519 && chmod 0600 /root/.ssh/id_ed25519
    - ssh -oStrictHostKeyChecking=no root@homeassistant.home.simcop2387.info -p 22222 'docker exec addon_a0d7b954_esphome sh -c "cd /config/esphome/; esphome compile garden-watering.yaml"'

#---
#kind: pipeline
#type: ssh
#name: deploy
#
#depends_on:
#  - build
#
#server:
#  host: homeassistant.private.simcop2387.info
#  user: esphome_remote
#  password:
#    from_secret:  esphome_remote_pass
#
#steps:
#- name: greeting
#  commands:
#  - echo hello world

