kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build_code
  image: perl
  commands:
  - cpanm --installdeps .
  - perl build_config.pl

- name: gitea_release
  image: plugins/gitea-release
  settings:
    files: garden-watering.yml
  when:
    event: tag

- name: upload
  image: plugins/s3
  settings:
    bucket: drone
    access_key:
      from_secret: drone_minio_user
    secret_key:
      from_secret: drone_minio_pass
    source: garden-watering.yaml
    target: /garden-water/
    path_style: true
    endpoint: http://192.168.132.1:9000

- name: push_to_homeass
  image: busybox
  secrets:
    - source: drone_homeassistant_ssh_key
      target: SSH_KEY
  commands:
    - mkdir /root/.ssh && echo "$${SSH_KEY}" > /root/.ssh/id_ed25519 && chmod 0600 /root/.ssh/id_ed25519
    - cat /root/.ssh/id_ed25519

#---
#kind: pipeline
#type: ssh
#name: deploy
#
#depends_on:
#  - build
#
#server:
#  host: homeassistant.private.simcop2387.info
#  user: esphome_remote
#  password:
#    from_secret:  esphome_remote_pass
#
#steps:
#- name: greeting
#  commands:
#  - echo hello world

